layout_spectrum: 0.2021712
typography_spectrum: 0.4495834
color:
  saturation: 0.8538355
  lightness: 0.7273498
  brandStrength: 0.4322186
  rhythmicContrast: 0.9225273
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: retail.place
